### ISSUE TITLE
Github Actions: Consider caching LLVM dirs on mac os

### ISSUE THREAD

**Issue by mattes** [pluto/web-prover#140]
```
- uses: actions/cache@v3
              id: cache-llvm-18
              with:
                 path: |
                  /usr/local/opt/llvm
                  /usr/local/Cellar/llvm/
                 key: ${{ runner.os }}-llvm-18  
```

Something like this.
